spring.application.name: gateway

ribbon:
  eureka:
    enabled: true

zuul:
  routes:
    member-api:
      path: /api/member/**   # zuul.routes.<serviceId>.path : 해당 path의 요청을 <serviceId>로 보낸다
      stripPrefix: false  # alse인 경우 uri를 모두 보내며(/api/members/1), true인 경우에는 matching된 값을 제외하고 보낸다(/1)


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 10000