DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS NOTIFICATION_RESULT;


CREATE TABLE NOTIFICATION (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DEVICE_TOKEN VARCHAR(64) NOT NULL,
  OS VARCHAR(10) NOT NULL,
  BUNDLE varchar(100) NOT NULL,
  PAYLOAD varchar(4000) NOT NULL,
  createdAt TIMESTAMP NOT NULL default now(),
  PRIMARY KEY (ID)
);

CREATE TABLE NOTIFICATION_RESULT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DEVICE_TOKEN VARCHAR(64) NOT NULL,
  MID varchar(32) NOT NULL,
  STATUS varchar(10),
  PRIMARY KEY (ID)
);